GET http://localhost:3000/api/v1

###
GET http://localhost:3000/api/v1/users



###
GET http://localhost:3000/api/v1/users/10


###
POST  http://localhost:3000/api/v1/users
Content-Type: application/json

{
    "name" : "Akhdan Robbani",
    "email" : "oukenzeuma@gmail.com", 
    "password" : "rahasia"
}

POST  http://localhost:3000/api/v1/users
Content-Type: application/json

{
    "name" : "akeon deofo",
    "email" : "akoennefo@gmail.com", 
    "password" : "rahasia"
}